import { template } from './template.ts';

export { template };

export const { createConfig } = template;

export { base, type BaseOptions } from './base.ts';
export {
  blockAllContributors,
  blockAreTheTypesWrong,
  blockBin,
  blockCodecov,
  blockCodeOfConduct,
  blockContributingDocs,
  blockCspell,
  blockDevelopmentDocs,
  blockEslint,
  blockEslintComments,
  blockEslintJsdoc,
  blockEslintJsonc,
  blockEslintMarkdown,
  blockEslintMarkdownLinks,
  blockEslintMoreStyling,
  blockEslintNode,
  blockEslintPackageJson,
  blockEslintPlugin,
  blockEslintRegexp,
  blockEslintYml,
  blockExports,
  blockFunding,
  blockGithubActionsCi,
  blockGithubIssueTemplates,
  blockGithubPrTemplate,
  blockGitignore,
  blockKnip,
  blockMitLicense,
  blockNcc,
  blockNvmrc,
  blockOctoguide,
  blockOctoguideStrict,
  blockPackageJson,
  blockPnpmDedupe,
  blockPnpmWorkspace,
  blockPrettier,
  blockPrettierPluginCurly,
  blockPrettierPluginPackageJson,
  blockPrettierPluginSentencesPerLine,
  blockPrettierPluginSh,
  blockReadme,
  blockReleasePlease,
  blockRenovate,
  blockSecurityDocs,
  blockSideEffects,
  blockTemplatedWith,
  blockTsdown,
  blockTypescript,
  blockVitest,
  blockVscode,
  blockWebExt,
} from './blocks/index.ts';
export type { Config } from './Config.ts';
export {
  presetCommon,
  presetEverything,
  presetMinimal,
} from './presets/index.ts';
