import { template } from './template.ts';

export { template };

export { base, type BaseOptions } from './base.ts';
export {
  blockAllContributors,
  blockAreTheTypesWrong,
  blockBin,
  type BlockBinProps,
  blockCodecov,
  blockCodeOfConduct,
  blockContributingDocs,
  blockCspell,
  type BlockCspellProps,
  blockDevelopmentDocs,
  type BlockDevelopmentDocsProps,
  blockEslint,
  blockEslintComments,
  blockEslintJsdoc,
  blockEslintJsonc,
  blockEslintMarkdown,
  blockEslintMarkdownLinks,
  blockEslintMoreStyling,
  blockEslintNode,
  blockEslintPackageJson,
  blockEslintPlugin,
  type BlockEslintPluginProps,
  type BlockEslintProps,
  blockEslintRegexp,
  blockEslintYml,
  blockExports,
  type BlockExportsProps,
  blockFunding,
  blockGitattributes,
  type BlockGitattributesProps,
  blockGithubActionsCi,
  type BlockGithubActionsCiProps,
  blockGithubIssueTemplates,
  blockGithubPrTemplate,
  blockGitignore,
  type BlockGitignoreProps,
  blockKnip,
  type BlockKnipProps,
  blockMitLicense,
  blockNcc,
  type BlockNccProps,
  blockNvmrc,
  blockOctoguide,
  type BlockOctoguideProps,
  blockOctoguideStrict,
  blockOxfmt,
  type BlockOxfmtProps,
  blockPackageJson,
  type BlockPackageJsonProps,
  blockPnpmDedupe,
  blockPnpmWorkspace,
  type BlockPnpmWorkspaceProps,
  blockPrettier,
  blockPrettierPluginSentencesPerLine,
  type BlockPrettierProps,
  blockPrPreviewRelease,
  type BlockPrPreviewReleaseProps,
  blockReadme,
  type BlockReadmeProps,
  blockReleasePlease,
  type BlockReleasePleaseProps,
  blockRenovate,
  type BlockRenovateProps,
  blockSecurityDocs,
  blockSideEffects,
  type BlockSideEffectsProps,
  blockTemplatedWith,
  blockTsdown,
  type BlockTsdownProps,
  blockTypescript,
  type BlockTypescriptProps,
  blockVitest,
  type BlockVitestProps,
  blockVscode,
  type BlockVscodeProps,
  blockWebExt,
  type BlockWithoutProps,
  type BlockWithProps,
} from './blocks/index.ts';
export { type Config, createConfig } from './Config.ts';
export { presetCommon, presetEverything, presetMinimal } from './presets/index.ts';
