import { template } from './template.ts';

export { template };

export const { createConfig } = template;

export { type BaseOptions, base } from './base.ts';
export {
  blockAllContributors,
  blockAreTheTypesWrong,
  blockBin,
  blockCodecov,
  blockCodeOfConduct,
  blockContributingDocs,
  blockCSpell,
  blockDevelopmentDocs,
  blockESLint,
  blockESLintComments,
  blockESLintJSDoc,
  blockESLintJSONC,
  blockESLintMarkdown,
  blockESLintMarkdownLinks,
  blockESLintMoreStyling,
  blockESLintNode,
  blockESLintPackageJson,
  blockESLintPlugin,
  blockESLintRegexp,
  blockESLintYML,
  blockExports,
  blockFunding,
  blockGitHubActionsCI,
  blockGitHubIssueTemplates,
  blockGitHubPRTemplate,
  blockGitignore,
  blockKnip,
  blockMITLicense,
  blockNcc,
  blockNvmrc,
  blockOctoGuide,
  blockOctoGuideStrict,
  blockPackageJson,
  blockPnpmDedupe,
  blockPnpmWorkspace,
  blockPrettier,
  blockPrettierPluginCurly,
  blockPrettierPluginPackageJson,
  blockPrettierPluginSentencesPerLine,
  blockPrettierPluginSh,
  blockREADME,
  blockReleasePlease,
  blockRenovate,
  blockSecurityDocs,
  blockSideEffects,
  blockTemplatedWith,
  blockTsdown,
  blockTypeScript,
  blockVitest,
  blockVSCode,
  blockWebExt,
} from './blocks/index.ts';
export type { Config, UserConfig } from './Config.ts';
export {
  presetCommon,
  presetEverything,
  presetMinimal,
} from './presets/index.ts';
