name: CI

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  are_the_types_wrong:
    name: Are the Types Wrong?
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm build
      - run: npx --yes @arethetypeswrong/cli --pack . --ignore-rules cjs-resolves-to-esm --profile esm-only

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm build
      - run: node ./dist/index.mjs

  dedupe_check:
    name: Dedupe Check
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm dedupe --check

  engines_check:
    name: Engines Check
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
        with:
          cache: false
          install-flags: --prod --ignore-scripts
          strict-engines: true

  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm format --list-different

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm lint

  lint_knip:
    name: Lint Knip
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm lint:knip

  lint_spelling:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm lint:spelling

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm run test --coverage
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          fail_ci_if_error: true
          use_oidc: true

  type_check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm tsc
